### PR TITLE
 feat: Product Detail page

### PR DESCRIPTION
**Pull request by PeeyushPrashant**
- add to cart from product detail page

Screenshot (111)

### CODE REVIEW

**Review by manish591 — APPROVED** [review]
Code is looking good, good to merge,
Few suggestions:
* use barrel imports
* use prettier for consistent formatting

**Review by Rohanmond — APPROVED** [review]
code looks good to merge

**Review by anuj-kumary — APPROVED** [review]
Code is looking good, good to merge,

**Review by vinc3nati — APPROVED** [review]
clean and concise code

**Pull request merged**
